---
title: "Reading Data from the Web"
author: "Alexis"
date: "10/10/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Get some data

read in the NSDUH data

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)

drug_use_xml

drug_use_xml %>%
  html_nodes(css  = "table")

table_list =
  drug_use_xml %>% html_nodes(css = "table")  
  table_list[[1]] %>%
    html_table()
 
tabl_marj =
  drug_use_xml %>% html_nodes(css = "table")  
  table_list[[1]] %>%
    html_table() %>%
    slice(-1) %>%
    as_tibble()
```

## get harry potter data

```{r}
hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")
```

```{r}
hp_movie_names =
  hpsaga_html %>%
  html_nodes(".lister-item-header a") %>%
  html_text() 

hp_movie_runtime =
  hpsaga_html %>%
  html_nodes(".runtime") %>%
  html_text() 

hp_movie_money =
  hpsaga_html %>%
  html_nodes(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

hp_df =
  tibble(
    title = hp_movie_names,
    runtime = hp_movie_runtime,
    money = hp_movie_money
  ) 
```

## get  napolean

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
) 
```


## Use API

```{r}
nyc_water_df =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content()
```

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

```{r}
brfss_data =
  GET("https://data.cdc.gov/api/views/waxm-p5qv/rows.csv?accessType=DOWNLOAD") %>%
content("parsed")
```

### when you are dealing with websites that periodically update, using APIs are useful

  
```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name
poke$abilities
```
  












