---
title: "Strings & Factors"
author: "Alexis"
date: "10/18/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## String manipulation

```{r}
string_vec = c("my", "name", "is", "jeff")


# does this pattern exist in this string: in string vector, find if Jeff exists 
str_detect(string_vec, "jeff")

str_detect(string_vec, "je")
```
```{r}
str_replace(string_vec, "jeff", "Jeff")

str_replace(string_vec, "m", "M")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")

# things that start with "i think"
str_detect(string_vec, "^i think")

# things that end with "i think"
str_detect(string_vec, "i think$")
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

# things that start with a capital b or lower case b but not all caps
str_detect(string_vec,"[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )


# want to detect a number followed by any letter
str_detect(string_vec, "^[0-9][a-zA-Z]")
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

# find everything that has a 7 followed by any character and an 11
str_detect(string_vec, "7.11")
```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

# open square bracket
str_detect(string_vec, pattern = "\\[")
```








